backend:
  - backend_host: "127.0.0.1"
    ports:
      - 8080
      - 8081
      - 8082


limiting:
  strategy: "no_limiting"
  rate: 1000000

load_balancing:
  strategy: "round_robin"

oxygen:
  port: 8000

health_check:
  interval_secs: 2
  check_type: "tcp"
