backend:
  - backend_host: "127.0.0.1"
    ports:
      - 8080
      - 8081
  - backend_host: "127.0.0.2"
    ports:
      - 9090

limiting:
  rate: 100

load_balancing:
  strategy: "round_robin"

oxygen:
  port: 8000